#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

target=$DIR/README.md

echo -n "Generating $target..."

sbt -batch --error "set showSuccess := false" "test:runMain docs.docGenerator" > $target

echo done

echo Wrote the generated markdown into $target

